name: Issues
on:
  issues:
    types:
      - opened
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{ toJSON(github) }}"
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"